# 1. Create and start container: docker-compose up -d --build
#
# 2. Log in to container: docker exec -it --user=dev_user spa_php-fpm bash
#
# 3. run composer install: composer install
#
# 4. Run migration and seed: php artisan migrate:fresh --seed
#
# 5. Access to http://127.0.0.1:8086
#     Mail : admin@admin.com
#     Pass : 12345678
#
# 6. (Access to phpMyAdmin is http://127.0.0.1:8087)

version: "3"
services:
  nginx:
    image: nginx:1.17
    container_name: spa_nginx
    depends_on:
      - php-fpm
      - vue
    ports:
      - 8086:80
    volumes:
      - ../../../api/:/usr/share/nginx/html:cached
      - ../../nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
  php-fpm:
    build: ../../php-fpm
    container_name: spa_php-fpm
    depends_on:
      - mysql
    volumes:
      - ../../../api/:/var/www/html:cached
      - ../../php-fpm/php.ini:/usr/local/etc/php/php.ini:cached
  mysql:
    image: mysql:5.7
    container_name: spa_mysql
    environment:
      MYSQL_DATABASE: db_spa
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: dev_pass
      TZ: Asia/Tokyo
    ports:
      - 3300:3306
    volumes:
      - spa-db-data:/var/lib/mysql:cached

  vue:
    build:
      context: ../../../.
      dockerfile: docker/vue/Dockerfile
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    container_name: spa_vue
    volumes:
      - /usr/src/app/node_modules
      - ../../../client/:/usr/src/app:cached

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    container_name: spa_phpmyadmin
    links:
      - mysql
    ports:
      - 8087:80
    volumes:
      - "../../phpmyadmin/sessions:/sessions"

  # ------------------ Testing container ------------------
#   mysql-test:
#     image: mysql:5.7
#     container_name: spa_mysql_test
#     environment:
#       MYSQL_DATABASE: db_spa
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_USER: dev_user
#       MYSQL_PASSWORD: dev_pass
#       TZ: Asia/Tokyo
#     ports:
#       - 3301:3306
#     volumes:
#       - spa-test-db-data:/var/lib/mysql:cached

#   phpmyadmin-test:
#     image: phpmyadmin/phpmyadmin
#     environment:
#       - PMA_ARBITRARY=1
#       - PMA_HOST=mysql-test
#       - PMA_USER=root
#       - PMA_PASSWORD=root
#     container_name: spa_test_phpmyadmin
#     links:
#       - mysql
#     ports:
#       - 8088:80
#     volumes:
#       - "../../phpmyadmin-test/sessions:/sessions"

#   selenium:
#     image: selenium/standalone-chrome-debug
#     ports:
#       - 4444:4444
#       - 5900:5900
#     container_name: spa_selenium
#     depends_on:
#       - nginx
#     privileged: true

volumes:
  spa-db-data:
    driver: local
  spa-test-db-data:
    driver: local
